"""creating tables (personal_info, parent_info, college_info, scholarship_applications, marksheets, documents)

Revision ID: 8280a641a7b5
Revises: 70b1d306f15f
Create Date: 2024-09-11 10:46:29.486171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8280a641a7b5'
down_revision: Union[str, None] = '70b1d306f15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_info',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('college_name', sa.String(length=300), nullable=False),
    sa.Column('degree', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('year_of_studying', sa.Integer(), nullable=False),
    sa.Column('college_address', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('parent_info',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('father_name', sa.String(length=50), nullable=False),
    sa.Column('father_occupation', sa.String(length=50), nullable=False),
    sa.Column('mother_name', sa.String(length=50), nullable=False),
    sa.Column('mother_occupation', sa.String(length=50), nullable=False),
    sa.Column('parent_mobile_num', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('personal_info',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('gheru_naav', sa.String(length=30), nullable=False),
    sa.Column('mobile_num', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('scholarship_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.Column('latest_sem_cgpa', sa.Float(precision=3, asdecimal=True), nullable=False),
    sa.Column('previous_sem_cgpa', sa.Float(precision=3, asdecimal=True), nullable=False),
    sa.Column('difference_in_cgpa', sa.Float(precision=3, asdecimal=True), nullable=False),
    sa.Column('arrears_in_previous_sem', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parental_info', sa.String(length=350), nullable=False),
    sa.Column('any_medical_issue', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('file_name', sa.String(length=30), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marksheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('encrypted_marksheet_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['scholarship_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marksheets')
    op.drop_table('student_documents')
    op.drop_table('scholarship_applications')
    op.drop_table('personal_info')
    op.drop_table('parent_info')
    op.drop_table('college_info')
    # ### end Alembic commands ###
