"""adding status column in scholarship_application_table

Revision ID: bdbfba9531b5
Revises: 8280a641a7b5
Create Date: 2024-09-11 19:03:16.987576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbfba9531b5'
down_revision: Union[str, None] = '8280a641a7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_applications', sa.Column('status', sa.String(length=30), server_default='pending', nullable=False))
    op.alter_column('scholarship_applications', 'latest_sem_cgpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=True),
               existing_nullable=False)
    op.alter_column('scholarship_applications', 'previous_sem_cgpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=True),
               existing_nullable=False)
    op.alter_column('scholarship_applications', 'difference_in_cgpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scholarship_applications', 'difference_in_cgpa',
               existing_type=sa.Float(precision=3, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('scholarship_applications', 'previous_sem_cgpa',
               existing_type=sa.Float(precision=3, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('scholarship_applications', 'latest_sem_cgpa',
               existing_type=sa.Float(precision=3, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('scholarship_applications', 'status')
    # ### end Alembic commands ###
